### ISSUE TITLE
Add plugin for context modelling. 

### ISSUE THREAD

**Issue by Invince11** [Vernacular-ai/dialogy#29]
Create a plugin for context modelling using the last bot utterance. The plugin should append the last bot-utteance to the user-utterance which will be then used as an input to the model. The example input structure is given below:
 `<bot_utterance> <SEP> <user_utterance>` where `user_utterance = <ASR hypothesis-1> <SEP> <ASR hypothesis-2> <SEP>...<SEP>`

Additionally, there should be a flag that makes it an optional feature.

**Comment by ltbringer** [comment]
To help you make this contribution, I would request you to go through an existing plugin.

The [plugin](https://vernacular-ai.github.io/dialogy/source/dialogy.preprocess.text.html#dialogy.preprocess.text.duckling_plugin.DucklingPlugin.plugin) method DucklingPlugin has is a good starting point to understand the inputs.

[[source](https://github.com/Vernacular-ai/dialogy/blob/72b00cab57004c8802d8234e218698f7c73d4f82/dialogy/preprocess/text/duckling_plugin.py#L300)]

In your case you probably should expect:

```python
input_, bot_utterance = access(workflow)
```
