### ISSUE TITLE
docstring rendering issue for ducklingplugin

### ISSUE THREAD

**Issue by greed2411** [Vernacular-ai/dialogy#34]
**Describe the bug**
Rendering of docstring docs for docstrings present for `timezone` parameter over [here](https://vernacular-ai.github.io/dialogy/source/dialogy.preprocess.text.html#dialogy.preprocess.text.duckling_plugin.DucklingPlugin)

**To Reproduce**
1. Visit [this](https://vernacular-ai.github.io/dialogy/source/dialogy.preprocess.text.html#dialogy.preprocess.text.duckling_plugin.DucklingPlugin)

**Expected behavior**
I think the intended behavior is not to break after the word in  `different` in `across different geographies and consistency`.

**Screenshots**
![image](https://user-images.githubusercontent.com/21098186/115203710-59ecac00-a115-11eb-9042-297a0524347c.png)

**Desktop (please complete the following information):**
 - Windows 10, firefox dev edition

**Comment by ltbringer** [comment]
Documentation will be revisited in the last week of September '21
