### ISSUE TITLE
Plugin for Inference Time Intent Aliasing 

### ISSUE THREAD

**Issue by hdidwania** [Vernacular-ai/dialogy#55]
**Is your feature request related to a problem? Please describe.**
Often it is needed to map the names of intents to some other name. This could be because of spelling mismatch [confirm -> _confirm_ ], merging intents [cash_withdrawal_issue -> cash_issue, cash_deposit_issue -> cash_issue], mapping to oos [ some_weird_intent -> _oos_ ], etc

**Describe the solution you'd like**
A plugin which takes a dictionary describing the mapping to be done. The plugin changes the name of the intent depending on this mapping.

**Comment by ltbringer** [comment]
This seems like a dialog management problem. I may pick this up depending on a change in my understanding of the feature.
