### ISSUE TITLE
Code breaks when duckling dimension "Amount-of-money" is used. 

### ISSUE THREAD

**Issue by Invince11** [Vernacular-ai/dialogy#58]
**Describe the bug**
When using dimensions like "amount-of-money" the code breaks [here](https://github.com/Vernacular-ai/dialogy/blob/master/dialogy/types/entity/__init__.py#L17).  There is no support for entities that are not listed here. 

**To Reproduce**
1. Add "amount-of-money" as one of the dimensions in duckling (predict.py file)
1. Run 'poetry run slu repl'
2. Enter '300 dollars'
3. Refer to the screenshot for the error traceback.

**Expected behavior**

**Screenshots**
![error_ducking](https://user-images.githubusercontent.com/31574850/122467659-69cf2200-cfd8-11eb-835e-c9aeff15a86b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu (e2e server)
 - Python version: 3.8.7
 
@greed2411 @ltbringer

**Comment by ltbringer** [comment]
Thank you for the report. We didn't have support for this entity, supported entities are [here](https://github.com/Vernacular-ai/dialogy/tree/master/dialogy/types/entity). To add support we need to add a `CurrencyEntity` It can inherit from `NumericalEntity`.
